DROP TABLE VERTEILER CASCADE CONSTRAINTS;
DROP TABLE PFANNE CASCADE CONSTRAINTS;
DROP TABLE KOKILLE CASCADE CONSTRAINTS;
DROP TABLE CHARGE CASCADE CONSTRAINTS;

DROP TABLE BEREICH CASCADE CONSTRAINTS;

DROP TABLE Produkt CASCADE CONSTRAINTS;
DROP TABLE EZV CASCADE CONSTRAINTS;
DROP TABLE PARAMETER CASCADE CONSTRAINTS;
DROP TABLE EZV_PARAM_MAPPING CASCADE CONSTRAINTS;
DROP TABLE TEXT_PARAM CASCADE CONSTRAINTS;
DROP TABLE Charge_Anlagenteil_Mapping CASCADE CONSTRAINTS;

CREATE TABLE VERTEILER (
    ID NUMBER,
    AGE NUMBER,
    CONSTRAINT PK_VERTEILER PRIMARY KEY (ID)
);

CREATE TABLE PFANNE (
    ID NUMBER,
    AGE NUMBER,
    CONSTRAINT PK_PFANNE PRIMARY KEY (ID)
);

CREATE TABLE KOKILLE (
    ID NUMBER,
    AGE NUMBER,
    CONSTRAINT PK_KOKILLE PRIMARY KEY (ID)
);

CREATE TABLE BEREICH (
    ID NUMBER,
    NAME VARCHAR2(32),
    CONSTRAINT PK_BEREICH PRIMARY KEY (ID)
);

CREATE TABLE PRODUKT (
    ID NUMBER,
    NAME varchar2(32),
    CONSTRAINT PK_PRODUKT PRIMARY KEY (ID)
);

CREATE TABLE EZV(
    ID NUMBER,
    NAME VARCHAR2(32),
    PRODUKT_ID NUMBER,
    
    CONSTRAINT PK_EZV PRIMARY KEY (ID),
    CONSTRAINT FK_EZV_PRODUKT FOREIGN KEY (PRODUKT_ID) REFERENCES PRODUKT(ID)
);

CREATE TABLE CHARGE(
    ID NUMBER,
    EZV_ID NUMBER,
    NAME VARCHAR2(100),
    CONSTRAINT PK_CHARGE PRIMARY KEY (ID)
);

CREATE TABLE Charge_Anlagenteil_Mapping(
    CHARGE_ID NUMBER,
    INGOING TIMESTAMP,
    OUTGOING TIMESTAMP,
    
    VERTEILER_ID NUMBER,
    PFANNE_ID NUMBER,
    KOKILLE_ID NUMBER
    
    --CONSTRAINT FK_CAM_Charge FOREIGN KEY (CHARGE_ID) REFERENCES CHARGE(ID),
    --CONSTRAINT FK_CAM_VERTEILER FOREIGN KEY (VERTEILER_ID) REFERENCES VERTEILER(ID),
    --CONSTRAINT FK_CAM_PFANNE FOREIGN KEY (PFANNE_ID) REFERENCES PFANNE(ID),
    --CONSTRAINT FK_CAM_KOKILLE FOREIGN KEY (KOKILLE_ID) REFERENCES KOKILLE(ID)
);

CREATE TABLE PARAMETER(
    ID NUMBER,
    NAME VARCHAR2(32),
    DEFAULT_VALUE NUMBER,
    TEXT_NUMBER NUMBER(1),
    EINHEIT VARCHAR2(32),
    MESSZEITPUNKT DATE,
    OBERGRENZE NUMBER,
    UNTERGRENZE NUMBER,
    BEREICH_ID NUMBER,
    CONSTRAINT PK_PARAMETER PRIMARY KEY (ID),
    CONSTRAINT FK_BEREICH FOREIGN KEY (BEREICH_ID) REFERENCES BEREICH(ID)
);

CREATE TABLE EZV_PARAM_MAPPING (
    ID NUMBER,
    EZV_ID NUMBER,
    PARAMETER_ID NUMBER,
    MIN NUMBER,
    AIM NUMBER,
    MAX NUMBER,
    CONSTRAINT PK_EZV_PARAM_MAPPING PRIMARY KEY (ID),
    CONSTRAINT FK_EZV_PARAM_MAPPING_EZV FOREIGN KEY (EZV_ID) REFERENCES EZV(ID),
    CONSTRAINT FK_EZV_PARAM_MAPPING_PARAMETER FOREIGN KEY (PARAMETER_ID) REFERENCES PARAMETER(ID)
);

CREATE TABLE TEXT_PARAM(
    PARAM_ID NUMBER,
    EquivalentNumber NUMBER,
    TEXT VARCHAR2(32),
    
    CONSTRAINT FK_TEXT_PARAM_PARAMETER FOREIGN KEY (PARAM_ID) REFERENCES PARAMETER(ID)
); --CONSTRAINT PK_TEXT_PARAM PRIMARY KEY (ID),